project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p16/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p16/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
      - href: index.qmd
        text: "Metadatenprofile f√ºr Testaufgaben: Deutsch Sek I"
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/p16
        aria-label: Source Code

lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
